"use client";

import { useMemo, useState } from "react";
import { AdminPageHeader } from "@/components/admin/page-header";
import { DataTable, type DataTableColumn } from "@/components/admin/data-table";
import { Modal } from "@/components/admin/modal";
import { StatusPill } from "@/components/admin/status-pill";
import { SelectField, TextAreaField, TextField } from "@/components/forms/fields";
import { useApiResource } from "@/hooks/use-api-resource";
import { api, ApiError } from "@/lib/api-client";
import { formatNaira, type MarketplaceCategory, type MarketplaceListing, type Paginated } from "@/lib/admin-types";

const conditions=[{label:"New",value:"new"},{label:"Used",value:"used"},{label:"Refurbished",value:"refurbished"},{label:"Certified Pre-Owned",value:"certified_pre_owned"}];
const statuses=[{label:"Draft",value:"draft"},{label:"Active",value:"active"},{label:"Reserved",value:"reserved"},{label:"Sold",value:"sold"},{label:"Out of Stock",value:"out_of_stock"},{label:"Archived",value:"archived"}];
const csv=(value:FormDataEntryValue|null)=>String(value??"").split(",").map(v=>v.trim()).filter(Boolean);

export default function MarketplacePage(){
  const {data:response,loading,error,refetch}=useApiResource<Paginated<MarketplaceListing>>("/admin/marketplace/listings");
  const {data:categories}=useApiResource<MarketplaceCategory[]>("/admin/marketplace/categories");
  const [editing,setEditing]=useState<MarketplaceListing|null>(null); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [formError,setFormError]=useState<string|null>(null); const [categorySlug,setCategorySlug]=useState(""); const [imageTarget,setImageTarget]=useState<MarketplaceListing|null>(null); const [variantTarget,setVariantTarget]=useState<MarketplaceListing|null>(null);
  const columns:DataTableColumn<MarketplaceListing>[]=useMemo(()=>[
    {key:"name",header:"Listing",render:r=><div><p className="text-white">{r.name}</p><p className="text-xs text-[var(--muted)]">{r.sku||r.slug}</p></div>},
    {key:"category",header:"Category",render:r=>r.category.name},{key:"price",header:"Price",render:r=>formatNaira(r.price)},
    {key:"stock",header:"Stock",render:r=>r.stock_quantity??"Untracked"},{key:"status",header:"Status",render:r=><StatusPill status={r.status}/>},
  ],[]);
  function begin(item:MarketplaceListing|null){setEditing(item);setCategorySlug(item?.category.slug??categories?.[0]?.slug??"");setFormError(null);setOpen(true)}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setFormError(null);const f=new FormData(event.currentTarget);const slug=String(f.get("category_slug"));const category=categories?.find(c=>c.slug===slug);if(!category)return;const payload:Record<string,unknown>={category_id:category.id,name:String(f.get("name")),slug:String(f.get("slug")),sku:String(f.get("sku"))||null,short_description:String(f.get("short_description"))||null,description:String(f.get("description"))||null,price:Number(f.get("price")),compare_at_price:f.get("compare_at_price")?Number(f.get("compare_at_price")):null,deposit_amount:f.get("deposit_amount")?Number(f.get("deposit_amount")):null,condition:String(f.get("condition")),status:String(f.get("status")),stock_quantity:f.get("stock_quantity")?Number(f.get("stock_quantity")):null,is_featured:f.get("is_featured")==="on",published_at:new Date().toISOString()};
    if(slug==="autos")payload.vehicle={make:String(f.get("make")),model:String(f.get("model")),year:Number(f.get("year")),mileage:f.get("mileage")?Number(f.get("mileage")):null,transmission:String(f.get("transmission"))||null,fuel_type:String(f.get("fuel_type"))||null,color:String(f.get("color"))||null,vin:String(f.get("vin"))||null,features:csv(f.get("features"))};
    if(slug==="fashion")payload.fashion={brand:String(f.get("brand"))||null,genders:csv(f.get("genders")),material:String(f.get("material"))||null,sizes:csv(f.get("sizes")),colors:csv(f.get("colors"))};
    if(slug==="gadgets")payload.gadget={brand:String(f.get("brand"))||null,model:String(f.get("gadget_model"))||null,storage:String(f.get("storage"))||null,memory:String(f.get("memory"))||null,warranty:String(f.get("warranty"))||null,specifications:{}};
    try{if(editing)await api.patch(`/admin/marketplace/listings/${editing.id}`,payload);else await api.post("/admin/marketplace/listings",payload);setOpen(false);refetch()}catch(e){setFormError(e instanceof ApiError?e.message:"Could not save listing.")}finally{setSaving(false)}}
  async function remove(item:MarketplaceListing){if(!confirm(`Delete “${item.name}”?`))return;await api.del(`/admin/marketplace/listings/${item.id}`);refetch()}
  async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!imageTarget)return;const updated=await api.post<MarketplaceListing>(`/admin/marketplace/listings/${imageTarget.id}/image`,new FormData(event.currentTarget));setImageTarget(updated);refetch();event.currentTarget.reset()}
  async function generateVariants(){if(!variantTarget)return;const updated=await api.post<MarketplaceListing>(`/admin/marketplace/listings/${variantTarget.id}/variants/generate`,{default_stock:0});setVariantTarget(updated);refetch()}
  async function updateVariant(event:React.FormEvent<HTMLFormElement>,variantId:number){event.preventDefault();if(!variantTarget)return;const f=new FormData(event.currentTarget);const updated=await api.patch<MarketplaceListing>(`/admin/marketplace/listings/${variantTarget.id}/variants/${variantId}`,{sku:String(f.get("sku"))||null,price:f.get("price")?Number(f.get("price")):null,stock_quantity:Number(f.get("stock_quantity")),is_active:f.get("is_active")==="on"});setVariantTarget(updated);refetch()}
  return <div className="space-y-6"><AdminPageHeader title="Marketplace" description="Manage autos, fashion, gadgets, and future FFSET Store categories from one catalogue." action={<button className="luxury-button luxury-button-primary px-4 py-2.5 text-xs" onClick={()=>begin(null)}>Add Listing</button>}/>
    {loading?<p className="p-8 text-[var(--muted)]">Loading marketplace…</p>:error?<p className="p-8 text-red-300">{error}</p>:<DataTable columns={columns} rows={response?.data??[]} rowKey={r=>r.id} emptyMessage="No marketplace listings yet." actions={r=><div className="flex gap-3"><button className="text-xs text-[var(--gold-soft)]" onClick={()=>begin(r)}>Edit</button>{r.category.slug==="fashion"?<button className="text-xs text-[var(--gold-soft)]" onClick={()=>setVariantTarget(r)}>Variants ({r.variants.length})</button>:null}<button className="text-xs text-[var(--gold-soft)]" onClick={()=>setImageTarget(r)}>Photos ({r.images.length})</button><button className="text-xs text-red-300" onClick={()=>remove(r)}>Delete</button></div>}/>} 
    <Modal open={open} onClose={()=>setOpen(false)} title={editing?"Edit Listing":"Add Listing"}><form className="space-y-4" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2">
      <SelectField label="Category" name="category_slug" value={categorySlug} onChange={e=>setCategorySlug(e.target.value)} options={(categories??[]).map(c=>({label:c.name,value:c.slug}))} required/><TextField label="Name" name="name" defaultValue={editing?.name} required/><TextField label="URL Slug" name="slug" defaultValue={editing?.slug} placeholder="iphone-16-pro" required/><TextField label="SKU" name="sku" defaultValue={editing?.sku??""}/><TextField label="Price (₦)" name="price" type="number" min={0} defaultValue={editing?.price} required/><TextField label="Compare Price (₦)" name="compare_at_price" type="number" min={0} defaultValue={editing?.compare_at_price??""}/><TextField label="Deposit (₦)" name="deposit_amount" type="number" min={0} defaultValue={editing?.deposit_amount??""}/><TextField label="Stock" name="stock_quantity" type="number" min={0} defaultValue={editing?.stock_quantity??""}/><SelectField label="Condition" name="condition" defaultValue={editing?.condition??"new"} options={conditions}/><SelectField label="Status" name="status" defaultValue={editing?.status??"draft"} options={statuses}/></div>
      <TextField label="Short Description" name="short_description" defaultValue={editing?.short_description??""}/><TextAreaField label="Full Description" name="description" defaultValue={editing?.description??""}/>
      {categorySlug==="autos"?<div className="grid gap-4 sm:grid-cols-2"><TextField label="Make" name="make" defaultValue={editing?.details?.make??""} required/><TextField label="Model" name="model" defaultValue={editing?.details?.model??""} required/><TextField label="Year" name="year" type="number" defaultValue={editing?.details?.year??""} required/><TextField label="Mileage" name="mileage" type="number" defaultValue={editing?.details?.mileage??""}/><TextField label="Transmission" name="transmission" defaultValue={editing?.details?.transmission??""}/><TextField label="Fuel Type" name="fuel_type" defaultValue={editing?.details?.fuel_type??""}/><TextField label="Color" name="color" defaultValue={editing?.details?.color??""}/><TextField label="VIN" name="vin" defaultValue={editing?.details?.vin??""}/><TextField label="Features (comma separated)" name="features" defaultValue={editing?.details?.features?.join(", ")??""}/></div>:null}
      {categorySlug==="fashion"?<div className="grid gap-4 sm:grid-cols-2"><TextField label="Brand" name="brand" defaultValue={editing?.fashion_details?.brand??""}/><TextField label="Genders (comma separated)" name="genders" defaultValue={editing?.fashion_details?.genders?.join(", ")??editing?.fashion_details?.gender??"unisex"} placeholder="men, women, unisex, kids"/><TextField label="Material" name="material" defaultValue={editing?.fashion_details?.material??""}/><TextField label="Sizes" name="sizes" defaultValue={editing?.fashion_details?.sizes.join(", ")??""}/><TextField label="Colors" name="colors" defaultValue={editing?.fashion_details?.colors.join(", ")??""}/></div>:null}
      {categorySlug==="gadgets"?<div className="grid gap-4 sm:grid-cols-2"><TextField label="Brand" name="brand" defaultValue={editing?.gadget_details?.brand??""}/><TextField label="Model" name="gadget_model" defaultValue={editing?.gadget_details?.model??""}/><TextField label="Storage" name="storage" defaultValue={editing?.gadget_details?.storage??""}/><TextField label="Memory / RAM" name="memory" defaultValue={editing?.gadget_details?.memory??""}/><TextField label="Warranty" name="warranty" defaultValue={editing?.gadget_details?.warranty??""}/></div>:null}
      <label className="flex items-center gap-2 text-sm text-white"><input type="checkbox" name="is_featured" defaultChecked={editing?.is_featured}/> Featured listing</label>{formError?<p className="text-red-300">{formError}</p>:null}<button disabled={saving} className="luxury-button luxury-button-primary w-full">{saving?"Saving…":"Save Listing"}</button></form></Modal>
    <Modal open={!!imageTarget} onClose={()=>setImageTarget(null)} title={`Photos — ${imageTarget?.name??""}`}><div className="grid grid-cols-3 gap-2">{imageTarget?.images.map(i=><div key={i.id} className="overflow-hidden rounded-lg">{/* eslint-disable-next-line @next/next/no-img-element */}<img src={i.image_url} alt={i.alt_text??""} className="h-24 w-full object-cover"/></div>)}</div><form className="mt-4 space-y-3" onSubmit={upload}><input className="form-input" type="file" name="image" accept="image/png,image/jpeg,image/webp" required/><TextField label="Alt text" name="alt_text"/><button className="luxury-button luxury-button-primary w-full">Upload Photo</button></form></Modal>
    <Modal open={!!variantTarget} onClose={()=>setVariantTarget(null)} title={`Variants — ${variantTarget?.name??""}`}><button type="button" className="luxury-button luxury-button-primary mb-4 w-full" onClick={generateVariants}>Generate missing combinations</button><div className="max-h-[60vh] space-y-3 overflow-y-auto">{variantTarget?.variants.map(variant=><form key={variant.id} onSubmit={event=>updateVariant(event,variant.id)} className="rounded-xl border border-white/8 p-3"><p className="mb-3 text-sm capitalize text-white">{Object.entries(variant.options).map(([key,value])=>`${key}: ${value}`).join(" · ")}</p><div className="grid gap-2 sm:grid-cols-3"><TextField label="SKU" name="sku" defaultValue={variant.sku??""}/><TextField label="Price override" name="price" type="number" min={0} defaultValue={variant.price??""}/><TextField label="Stock" name="stock_quantity" type="number" min={0} defaultValue={variant.stock_quantity} required/></div><label className="mt-2 flex gap-2 text-xs text-white"><input type="checkbox" name="is_active" defaultChecked={variant.is_active}/> Available</label><button className="mt-3 text-xs text-[var(--gold-soft)]">Save variant</button></form>)}</div></Modal>
  </div>
}
