"use client";
import {useMemo,useState} from "react";
import {AdminPageHeader} from "@/components/admin/page-header";import {DataTable,type DataTableColumn} from "@/components/admin/data-table";import {Modal} from "@/components/admin/modal";import {StatusPill} from "@/components/admin/status-pill";import {useApiResource} from "@/hooks/use-api-resource";import {api,ApiError} from "@/lib/api-client";import {formatNaira,type MarketplaceOrder,type Paginated} from "@/lib/admin-types";
export default function MarketplaceOrdersPage(){const {data,loading,error,refetch}=useApiResource<Paginated<MarketplaceOrder>>("/admin/marketplace/orders");const [selected,setSelected]=useState<MarketplaceOrder|null>(null);const [actionError,setActionError]=useState<string|null>(null);const columns:DataTableColumn<MarketplaceOrder>[]=useMemo(()=>[
{key:"reference",header:"Reference",render:r=><button className="text-[var(--gold-soft)] hover:underline" onClick={()=>setSelected(r)}>{r.reference_code}</button>},{key:"customer",header:"Customer",render:r=><div>{r.name}<p className="text-xs text-[var(--muted)]">{r.phone}</p></div>},{key:"items",header:"Items",render:r=>r.items.map(i=>`${i.listing_name} ×${i.quantity}`).join(", ")},{key:"total",header:"Total",render:r=>formatNaira(r.total)},{key:"payment",header:"Payment",render:r=><StatusPill status={r.payment_status}/>},{key:"status",header:"Fulfilment",render:r=><StatusPill status={r.status}/>},],[]);
async function update(body:object){if(!selected)return;setActionError(null);try{const result=await api.patch<MarketplaceOrder>(`/admin/marketplace/orders/${selected.id}`,body);setSelected(result);refetch()}catch(e){setActionError(e instanceof ApiError?e.message:"Could not update order.")}}
async function refund(){if(!selected)return;const reason=window.prompt("Refund reason");if(!reason)return;try{const result=await api.post<MarketplaceOrder>(`/admin/marketplace/orders/${selected.id}/refund`,{reason});setSelected(result);refetch()}catch(e){setActionError(e instanceof ApiError?e.message:"Refund failed.")}}
return <div className="space-y-6"><AdminPageHeader title="Store Orders" description="Marketplace payments, variants, delivery, fulfilment, and refunds."/>{loading?<p>Loading…</p>:error?<p className="text-red-300">{error}</p>:<DataTable columns={columns} rows={data?.data??[]} rowKey={r=>r.id} emptyMessage="No store orders yet." actions={r=><button className="text-xs text-[var(--gold-soft)]" onClick={()=>setSelected(r)}>View order</button>}/>}<Modal open={!!selected} onClose={()=>setSelected(null)} title={`Order ${selected?.reference_code??""}`}>
{selected?<div className="space-y-5 print:text-black"><div className="grid gap-3 sm:grid-cols-2"><div><p className="form-label">Customer</p><p className="mt-1 text-white">{selected.name}</p><p className="text-sm text-[var(--muted)]">{selected.phone}<br/>{selected.email}</p></div><div><p className="form-label">Fulfilment</p><p className="mt-1 capitalize text-white">{selected.fulfillment_type} · {selected.status.replaceAll("_"," ")}</p><p className="text-sm text-[var(--muted)]">{selected.delivery_zone?.name}{selected.delivery_address?<><br/>{selected.delivery_address}</>:null}</p></div></div>
<div><p className="form-label">Packing list</p><div className="mt-2 divide-y divide-white/8 rounded-xl border border-white/8">{selected.items.map(item=><div key={item.id} className="flex justify-between gap-3 p-3"><div><p className="text-white">{item.listing_name} × {item.quantity}</p><p className="text-xs text-[var(--muted)]">{item.listing_sku??"No SKU"} · {item.purchase_type}</p>{Object.keys(item.selected_options).length?<p className="mt-1 text-xs capitalize text-[var(--gold-soft)]">{Object.entries(item.selected_options).map(([k,v])=>`${k}: ${v}`).join(" · ")}</p>:null}</div><p>{formatNaira(item.line_total)}</p></div>)}</div></div>
<div className="space-y-1 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{formatNaira(selected.subtotal)}</span></div><div className="flex justify-between"><span>Delivery</span><span>{formatNaira(selected.delivery_fee)}</span></div><div className="flex justify-between border-t border-white/8 pt-2 text-lg text-white"><span>Total</span><span>{formatNaira(selected.total)}</span></div></div>
{selected.payment_attempts?.length?<div><p className="form-label">Payment audit</p>{selected.payment_attempts.map(attempt=><p key={attempt.id} className="mt-2 text-xs text-[var(--muted)]">{attempt.reference} · {attempt.status} · {formatNaira(attempt.amount)}</p>)}</div>:null}
<div className="grid gap-3 sm:grid-cols-2"><textarea id="internal_notes" className="form-input" defaultValue={selected.internal_notes??""} placeholder="Internal notes"/><input id="tracking_reference" className="form-input" defaultValue={selected.tracking_reference??""} placeholder="Tracking reference"/></div>{actionError?<p className="text-sm text-red-300">{actionError}</p>:null}
<div className="flex flex-wrap gap-2"><button className="luxury-button luxury-button-secondary" onClick={()=>window.print()}>Print packing slip</button>{selected.payment_status==="unpaid"?<button className="luxury-button luxury-button-primary" onClick={()=>update({payment_status:"paid",status:"confirmed"})}>Confirm bank payment</button>:null}{selected.status==="confirmed"?<button className="luxury-button luxury-button-primary" onClick={()=>update({status:"processing",internal_notes:(document.getElementById("internal_notes") as HTMLTextAreaElement)?.value})}>Start processing</button>:null}{selected.status==="processing"&&selected.fulfillment_type==="pickup"?<button className="luxury-button luxury-button-primary" onClick={()=>update({status:"ready_for_pickup"})}>Ready for pickup</button>:null}{selected.status==="processing"&&selected.fulfillment_type==="delivery"?<button className="luxury-button luxury-button-primary" onClick={()=>update({status:"dispatched",tracking_reference:(document.getElementById("tracking_reference") as HTMLInputElement)?.value})}>Dispatch</button>:null}{["ready_for_pickup","dispatched"].includes(selected.status)?<button className="luxury-button luxury-button-primary" onClick={()=>update({status:"delivered"})}>Mark delivered</button>:null}{selected.status==="pending"?<button className="luxury-button luxury-button-secondary" onClick={()=>update({status:"cancelled",cancellation_reason:"Cancelled by admin"})}>Cancel</button>:null}{selected.payment_status==="paid"?<button className="luxury-button luxury-button-secondary text-red-300" onClick={refund}>Refund</button>:null}</div>
</div>:null}</Modal></div>}
